dbs:
  - path: /app/public/data/reports.db
    replicas:
      - type: s3
        endpoint: https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
        bucket: ${LITESTREAM_BUCKET}
        path: reports
        access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
        secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
        region: auto
